import {Food} from './app/shared/models/Food';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Spicy chicken curry recipe',
    cookTime: '20-30',
    price: 180,
    favorite: false,
    origins: ['Andhra'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['Curry', 'Chicken', 'Lunch'],
  },
  {
    id:'2',
    name: 'Kara chutney with idli',
    price: 60,
    cookTime: '10-20',
    favorite: true,
    origins: ['south-indian', 'ceylon'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Breakfast', 'Dinner'],
  },
  {
    id:'3',
    name: 'Egg gravy recipe',
    price: 80,
    cookTime: '10-15',
    favorite: false,
    origins: ['indian', 'srilankan'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['Egg', 'Curry', 'Lunch'],
  },
  {
    id:'4',
    name: 'Beetroot fry',
    price: 35,
    cookTime: '10-15',
    favorite: true,
    origins: ['Tamilnadu', 'Kerala'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['Veggie', 'Fry'],
  },
  {
    id:'5',
    name: 'Neer mor, South Indian buttermilk recipe',
    price: 20,
    cookTime: '0-5',
    favorite: false,
    origins: ['south-indian', 'srilankan'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'drinks'],
  },
  {
    id:'6',
    name: 'Keerai vadai',
    price: 9,
    cookTime: '10-15',
    favorite: false,
    origins: ['south-indian'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Snacks'],
  },
]
